"""add_indexes_to_database

Revision ID: 29f973886d8f
Revises: 70b01735cc6a
Create Date: 2025-12-03 10:24:33.985521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f973886d8f'
down_revision = '70b01735cc6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_name'), 'notifications', ['recipient_name'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_notifications_work_order_id'), 'notifications', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_requests_assigned_to'), 'requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_created_by'), 'requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_requests_preferred_date'), 'requests', ['preferred_date'], unique=False)
    op.create_index(op.f('ix_requests_priority'), 'requests', ['priority'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_workorders_assigned_to'), 'workorders', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_workorders_due_date'), 'workorders', ['due_date'], unique=False)
    op.create_index(op.f('ix_workorders_priority'), 'workorders', ['priority'], unique=False)
    op.create_index(op.f('ix_workorders_status'), 'workorders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workorders_status'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_priority'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_due_date'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_assigned_to'), table_name='workorders')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_priority'), table_name='requests')
    op.drop_index(op.f('ix_requests_preferred_date'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_by'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_index(op.f('ix_requests_assigned_to'), table_name='requests')
    op.drop_index(op.f('ix_notifications_work_order_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_name'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    # ### end Alembic commands ###