"""add_team_id_to_user

Revision ID: 396d32a5d21a
Revises: 25f849862468
Create Date: 2025-12-09 14:33:57.344066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396d32a5d21a'
down_revision = '25f849862468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.add_column('workorders', sa.Column('managed_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workorders', 'managed_by')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###