"""sync_schema_updates

Revision ID: 4d1f3e4cedfd
Revises: b25bf006b338
Create Date: 2025-12-03 09:40:51.686776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1f3e4cedfd'
down_revision = 'b25bf006b338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_name'), 'notifications', ['recipient_name'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_notifications_work_order_id'), 'notifications', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_requests_assigned_to'), 'requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_created_by'), 'requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_requests_preferred_date'), 'requests', ['preferred_date'], unique=False)
    op.create_index(op.f('ix_requests_priority'), 'requests', ['priority'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_workorders_assigned_to'), 'workorders', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_workorders_due_date'), 'workorders', ['due_date'], unique=False)
    op.create_index(op.f('ix_workorders_priority'), 'workorders', ['priority'], unique=False)
    op.create_index(op.f('ix_workorders_status'), 'workorders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workorders_status'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_priority'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_due_date'), table_name='workorders')
    op.drop_index(op.f('ix_workorders_assigned_to'), table_name='workorders')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_priority'), table_name='requests')
    op.drop_index(op.f('ix_requests_preferred_date'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_by'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_index(op.f('ix_requests_assigned_to'), table_name='requests')
    op.drop_index(op.f('ix_notifications_work_order_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_name'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###