"""add_media_type_to_images

Revision ID: 604bd8654649
Revises: e887c76af8c0
Create Date: 2025-12-11 17:53:15.734229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604bd8654649'
down_revision = 'e887c76af8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('media_type', sa.String(length=10), nullable=False, server_default='image'))
    op.add_column('images', sa.Column('content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'content_type')
    op.drop_column('images', 'media_type')
    # ### end Alembic commands ###