"""add_oauth_states

Revision ID: a82b71e95d96
Revises: db1b4b07ebf3
Create Date: 2025-12-04 15:32:47.151581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82b71e95d96'
down_revision = 'db1b4b07ebf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('nonce', sa.String(length=100), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_states')
    # ### end Alembic commands ###