"""create_asset_phase1_complete

Revision ID: c83e8c542b7f
Revises: 604bd8654649
Create Date: 2025-12-15 09:47:26.569577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83e8c542b7f'
down_revision = '604bd8654649'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.String(length=50), nullable=True),
    sa.Column('warranty_expiry', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_parent_id'), 'assets', ['parent_id'], unique=False)
    op.create_table('asset_downtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('production_loss', sa.Float(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_downtimes_asset_id'), 'asset_downtimes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_downtimes_id'), 'asset_downtimes', ['id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('reading_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_asset_id'), 'meter_readings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_asset_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_asset_downtimes_id'), table_name='asset_downtimes')
    op.drop_index(op.f('ix_asset_downtimes_asset_id'), table_name='asset_downtimes')
    op.drop_table('asset_downtimes')
    op.drop_index(op.f('ix_assets_parent_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###