"""
Functional Location Models for Eureka CMMS

This module defines the Pydantic models for functional location management in the
multi-site, multi-tenant architecture. Functional locations represent WHERE things
are located (hierarchical structure: Plant → Building → Floor → Area → Line → Station).

Models:
    - LocationType: Enum for location type classification
    - LocationStatus: Enum for location operational status
    - FunctionalLocationBase: Base model with shared fields
    - FunctionalLocationCreate: Model for creating new functional locations
    - FunctionalLocationUpdate: Model for updating existing functional locations
    - FunctionalLocation: Full functional location model with all fields
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class LocationType(str, Enum):
    """
    Type of location determines its role in the hierarchy and available workflows.
    
    - plant: Top-level facility
    - building: Physical structure
    - floor: Building level
    - area: Functional area
    - line: Production line
    - station: Work station
    - room: Room within building
    - zone: Zone/region
    - other: Custom location types
    """
    PLANT = "plant"
    BUILDING = "building"
    FLOOR = "floor"
    AREA = "area"
    LINE = "line"
    STATION = "station"
    ROOM = "room"
    ZONE = "zone"
    OTHER = "other"


class LocationStatus(str, Enum):
    """
    Location operational status.
    
    - active: Location is in use and appears in asset assignment and work orders
    - inactive: Location is decommissioned or no longer used, data preserved
               for historical reporting but excluded from active operations
    """
    ACTIVE = "active"
    INACTIVE = "inactive"


class FunctionalLocationBase(BaseModel):
    """
    Base functional location model with shared fields for create and update operations.
    """
    
    # Location identification
    name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Display name shown throughout the application (e.g., 'Production Line 1')"
    )
    
    # Location classification
    location_type: LocationType = Field(
        LocationType.AREA,
        description="Type of location: plant, building, floor, area, line, station, room, zone, or other"
    )
    
    description: Optional[str] = Field(
        None,
        description="Detailed description of the location, its purpose, and any relevant notes"
    )
    
    # Hierarchy management
    parent_id: Optional[UUID] = Field(
        None,
        description="Foreign key to parent functional location (self-reference). NULL for root locations"
    )
    
    level: int = Field(
        0,
        ge=0,
        description="Hierarchy depth level (0 = root, 1 = first child, etc.). Calculated automatically"
    )
    
    path: str = Field(
        "/",
        description="Materialized path for efficient tree queries (e.g., '/PLANT-A/BLDG-1/LINE-1')"
    )
    
    # Location information
    latitude: Optional[Decimal] = Field(
        None,
        ge=-90,
        le=90,
        description="GPS latitude coordinate (decimal degrees, -90 to 90)"
    )
    
    longitude: Optional[Decimal] = Field(
        None,
        ge=-180,
        le=180,
        description="GPS longitude coordinate (decimal degrees, -180 to 180)"
    )
    
    qr_code: Optional[str] = Field(
        None,
        max_length=100,
        description="QR code string for mobile scanning. Auto-generated on creation or manually assigned"
    )
    
    # Flexible settings storage
    settings: Dict[str, Any] = Field(
        default_factory=dict,
        description="Flexible JSON storage for location-specific configurations"
    )


class FunctionalLocationCreate(FunctionalLocationBase):
    """
    Model for creating a new functional location.
    
    The location code is auto-generated by the system (e.g., FL-PLANT-A-LINE1),
    so it's not included in the create request.
    The tenant_id and site_id are typically set from the authenticated user's context.
    """
    pass


class FunctionalLocationUpdate(BaseModel):
    """
    Model for updating an existing functional location.
    
    All fields are optional - only provided fields will be updated.
    The location code and ID cannot be changed after creation.
    """
    
    name: Optional[str] = Field(
        None,
        min_length=1,
        max_length=255,
        description="Display name shown throughout the application"
    )
    
    location_type: Optional[LocationType] = Field(
        None,
        description="Type of location"
    )
    
    description: Optional[str] = Field(
        None,
        description="Detailed description of the location"
    )
    
    parent_id: Optional[UUID] = Field(
        None,
        description="Foreign key to parent functional location (self-reference)"
    )
    
    level: Optional[int] = Field(
        None,
        ge=0,
        description="Hierarchy depth level (0 = root, 1 = first child, etc.)"
    )
    
    path: Optional[str] = Field(
        None,
        description="Materialized path for efficient tree queries"
    )
    
    latitude: Optional[Decimal] = Field(
        None,
        ge=-90,
        le=90,
        description="GPS latitude coordinate"
    )
    
    longitude: Optional[Decimal] = Field(
        None,
        ge=-180,
        le=180,
        description="GPS longitude coordinate"
    )
    
    qr_code: Optional[str] = Field(
        None,
        max_length=100,
        description="QR code string for mobile scanning"
    )
    
    status: Optional[LocationStatus] = Field(
        None,
        description="Location operational status"
    )
    
    settings: Optional[Dict[str, Any]] = Field(
        None,
        description="Location-specific configurations"
    )


class FunctionalLocation(FunctionalLocationBase):
    """
    Full functional location model representing a record in the database.
    
    Includes all base fields plus system-managed fields like ID, code,
    tenant_id, site_id, status, and audit timestamps.
    """
    
    # System-generated identifier (UUID)
    id: UUID = Field(
        ...,
        description="Unique identifier for the functional location (UUID)"
    )
    
    # Foreign key to parent tenant
    tenant_id: UUID = Field(
        ...,
        description="Foreign key to the parent tenant for multi-tenant data isolation"
    )
    
    # Foreign key to parent site
    site_id: UUID = Field(
        ...,
        description="Foreign key to the site where this location exists"
    )
    
    # Human-readable location code (auto-generated, e.g., FL-PLANT-A-LINE1)
    code: str = Field(
        ...,
        max_length=50,
        description="Human-readable location code for UI and reports"
    )
    
    # Location status
    status: LocationStatus = Field(
        LocationStatus.ACTIVE,
        description="Location operational status: active or inactive"
    )
    
    # Audit timestamps
    created_at: datetime = Field(
        ...,
        description="Timestamp when location was created"
    )
    
    updated_at: datetime = Field(
        ...,
        description="Timestamp of last modification"
    )
    
    # Audit user references (UUID of the user who performed the action)
    created_by: Optional[UUID] = Field(
        None,
        description="User ID of Site Manager or Tenant Admin who created this location"
    )
    
    updated_by: Optional[UUID] = Field(
        None,
        description="User ID who last modified this location record"
    )

    class Config:
        """Pydantic configuration."""
        from_attributes = True  # Enable ORM mode for SQLAlchemy compatibility

